package api

import (
	"context"
	"errors"
	"fmt"
	"log"
	"net/http"
	"strconv"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/daydemir/stoarama/backend/internal/util"
)

// NAS upload speed probe.
//
// The NAS pull client periodically asks for a probe target. The API decides
// whether a probe is due (config interval per connection), reserves a row, and
// returns one exact-length presigned PUT per stream under nas-probes/. The
// client uploads generated bytes, measures wall time, and reports the result.
// The API deletes the probe objects once the result arrives, and sweeps any
// probe whose target expired without a report. Nothing here touches recorded
// content: the only writable keys are the ones this file generates.

const (
	nasUploadProbePrefix      = "nas-probes/"
	nasUploadProbeTTL         = 30 * time.Minute
	nasUploadProbeSweepGrace  = 30 * time.Minute
	nasUploadProbeSweepLimit  = 20
	nasUploadProbeMaxError    = 500
	nasUploadProbeMaxDuration = 24 * time.Hour
	nasUploadProbeDisabledSec = 3600
	nasUploadProbeContentType = "application/octet-stream"
)

type nasUploadProbeRequest struct {
	ClientVersion string `json:"client_version"`
}

type nasUploadProbePart struct {
	URL       string            `json:"url"`
	Method    string            `json:"method"`
	Headers   map[string]string `json:"headers"`
	SizeBytes int64             `json:"size_bytes"`
}

type nasUploadProbeResponse struct {
	Enabled       bool                 `json:"enabled"`
	Due           bool                 `json:"due"`
	RetryAfterSec int                  `json:"retry_after_sec"`
	ProbeID       int64                `json:"probe_id,omitempty"`
	SizeBytes     int64                `json:"size_bytes,omitempty"`
	Streams       int                  `json:"streams,omitempty"`
	ExpiresAt     *time.Time           `json:"expires_at,omitempty"`
	Parts         []nasUploadProbePart `json:"parts,omitempty"`
}

type nasUploadProbeResultRequest struct {
	BytesUploaded        int64      `json:"bytes_uploaded"`
	DurationMS           int64      `json:"duration_ms"`
	StartedAt            *time.Time `json:"started_at"`
	Error                string     `json:"error"`
	ClientVersion        string     `json:"client_version"`
	ClientPhaseStart     string     `json:"client_phase_start"`
	ClientPhaseEnd       string     `json:"client_phase_end"`
	JoinedTransferActive bool       `json:"joined_transfer_active"`
	BytesPulledDuring    int64      `json:"bytes_pulled_during"`
}

// nasUploadProbePartSizes splits size evenly over streams; the last part
// carries the remainder so the parts always sum to size.
func nasUploadProbePartSizes(size int64, streams int) []int64 {
	parts := make([]int64, streams)
	base := size / int64(streams)
	for i := range parts {
		parts[i] = base
	}
	parts[streams-1] += size - base*int64(streams)
	return parts
}

func nasUploadProbeKeys(prefix string, streams int) []string {
	keys := make([]string, streams)
	for i := range keys {
		keys[i] = prefix + "/part-" + strconv.Itoa(i)
	}
	return keys
}

// nasUploadProbeMbps is megabits per second of wall time.
func nasUploadProbeMbps(bytes, durationMS int64) float64 {
	if durationMS <= 0 {
		return 0
	}
	return float64(bytes) * 8 / (float64(durationMS) / 1000) / 1e6
}

// nasUploadProbeDue reports whether a new probe may start, and otherwise how
// long until it may. A pending unexpired probe always blocks a new one.
func nasUploadProbeDue(now time.Time, lastCreated *time.Time, pendingUntil *time.Time, interval time.Duration) (bool, time.Duration) {
	if pendingUntil != nil && now.Before(*pendingUntil) {
		return false, pendingUntil.Sub(now)
	}
	if lastCreated == nil {
		return true, 0
	}
	next := lastCreated.Add(interval)
	if !now.Before(next) {
		return true, 0
	}
	return false, next.Sub(now)
}

func validateNASUploadProbeResult(req nasUploadProbeResultRequest, sizeBytes int64, now time.Time) error {
	if req.BytesUploaded < 0 || req.BytesUploaded > sizeBytes {
		return errors.New("bytes_uploaded must be between 0 and the probe size")
	}
	if req.DurationMS < 1 || req.DurationMS > nasUploadProbeMaxDuration.Milliseconds() {
		return errors.New("duration_ms must be between 1 and 86400000")
	}
	if req.StartedAt == nil || req.StartedAt.After(now.Add(connectionHeartbeatFutureSkew)) {
		return errors.New("started_at is required and may not be in the future")
	}
	if len(req.Error) > nasUploadProbeMaxError {
		return errors.New("error is too long")
	}
	if req.BytesUploaded < sizeBytes && req.Error == "" {
		return errors.New("a partial upload requires an error")
	}
	if req.BytesPulledDuring < 0 {
		return errors.New("bytes_pulled_during must be non-negative")
	}
	if req.ClientVersion != "" && (len(req.ClientVersion) > 64 || !relayArtifactName.MatchString(req.ClientVersion)) {
		return errors.New("invalid client_version")
	}
	for _, phase := range []string{req.ClientPhaseStart, req.ClientPhaseEnd} {
		if phase != "" && !connectionPhases[phase] {
			return errors.New("invalid client phase")
		}
	}
	return nil
}

func (s *Server) nasUploadProbeConnection(ctx context.Context, q pgx.Tx, w http.ResponseWriter, r *http.Request) (int64, bool) {
	principal, ok := accountPrincipalFromContext(r.Context())
	if !ok {
		util.WriteError(w, http.StatusUnauthorized, "unauthorized")
		return 0, false
	}
	if principal.APIKeyID == nil {
		util.WriteError(w, http.StatusForbidden, "upload probe requires a NAS pull key")
		return 0, false
	}
	var connectionID int64
	err := q.QueryRow(ctx, `SELECT id FROM connections WHERE api_key_id=$1 AND account_id=$2 AND kind='nas_pull' FOR UPDATE`,
		*principal.APIKeyID, principal.AccountID).Scan(&connectionID)
	if errors.Is(err, pgx.ErrNoRows) {
		util.WriteError(w, http.StatusForbidden, "no connection for this key")
		return 0, false
	}
	if err != nil {
		util.WriteError(w, http.StatusInternalServerError, "load upload probe connection failed")
		return 0, false
	}
	return connectionID, true
}

// handleAccountConnectionUploadProbe issues an upload probe target when one is
// due. It always returns retry_after_sec so the client never needs its own
// schedule configuration.
func (s *Server) handleAccountConnectionUploadProbe(w http.ResponseWriter, r *http.Request) {
	var req nasUploadProbeRequest
	if err := util.DecodeJSON(r, &req); err != nil {
		util.WriteError(w, http.StatusBadRequest, err.Error())
		return
	}
	if req.ClientVersion != "" && (len(req.ClientVersion) > 64 || !relayArtifactName.MatchString(req.ClientVersion)) {
		util.WriteError(w, http.StatusBadRequest, "invalid client_version")
		return
	}
	ctx := r.Context()
	if !s.cfg.NASUploadProbeEnabled || s.r2 == nil {
		// Still authenticate: a disabled probe must not become an oracle for
		// unauthenticated callers, and the NAS key must still own a connection.
		tx, err := s.pool.Begin(ctx)
		if err != nil {
			util.WriteError(w, http.StatusInternalServerError, "begin upload probe failed")
			return
		}
		defer func() { _ = tx.Rollback(ctx) }()
		if _, ok := s.nasUploadProbeConnection(ctx, tx, w, r); !ok {
			return
		}
		util.WriteJSON(w, http.StatusOK, nasUploadProbeResponse{RetryAfterSec: nasUploadProbeDisabledSec})
		return
	}
	s.sweepNASUploadProbes(ctx)

	tx, err := s.pool.Begin(ctx)
	if err != nil {
		util.WriteError(w, http.StatusInternalServerError, "begin upload probe failed")
		return
	}
	defer func() { _ = tx.Rollback(ctx) }()
	connectionID, ok := s.nasUploadProbeConnection(ctx, tx, w, r)
	if !ok {
		return
	}
	var lastCreated, pendingUntil *time.Time
	var now time.Time
	if err := tx.QueryRow(ctx, `
		SELECT now(),
		       (SELECT max(created_at) FROM nas_upload_probes WHERE connection_id=$1),
		       (SELECT max(expires_at) FROM nas_upload_probes WHERE connection_id=$1 AND reported_at IS NULL)`,
		connectionID).Scan(&now, &lastCreated, &pendingUntil); err != nil {
		util.WriteError(w, http.StatusInternalServerError, "load upload probe history failed")
		return
	}
	interval := s.cfg.NASUploadProbeInterval
	due, wait := nasUploadProbeDue(now, lastCreated, pendingUntil, interval)
	if !due {
		util.WriteJSON(w, http.StatusOK, nasUploadProbeResponse{Enabled: true, RetryAfterSec: int(wait.Seconds()) + 1})
		return
	}

	size := int64(s.cfg.NASUploadProbeBytes)
	streams := s.cfg.NASUploadProbeStreams
	expires := now.Add(nasUploadProbeTTL)
	var probeID int64
	if err := tx.QueryRow(ctx, `SELECT nextval(pg_get_serial_sequence('nas_upload_probes','id'))`).Scan(&probeID); err != nil {
		util.WriteError(w, http.StatusInternalServerError, "reserve upload probe failed")
		return
	}
	prefix := fmt.Sprintf("%s%d/%s-%d", nasUploadProbePrefix, connectionID, now.UTC().Format("20060102T150405Z"), probeID)
	if _, err := tx.Exec(ctx, `
		INSERT INTO nas_upload_probes (id,connection_id,object_prefix,size_bytes,streams,created_at,expires_at,client_version)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,
		probeID, connectionID, prefix, size, streams, now, expires, req.ClientVersion); err != nil {
		util.WriteError(w, http.StatusInternalServerError, "record upload probe failed")
		return
	}
	keys := nasUploadProbeKeys(prefix, streams)
	sizes := nasUploadProbePartSizes(size, streams)
	parts := make([]nasUploadProbePart, streams)
	for i := range parts {
		presigned, err := s.r2.PresignPutSizedRequest(ctx, keys[i], nasUploadProbeContentType, sizes[i], nasUploadProbeTTL)
		if err != nil {
			util.WriteError(w, http.StatusInternalServerError, "presign upload probe failed")
			return
		}
		headers := map[string]string{}
		for name, values := range presigned.Headers {
			if http.CanonicalHeaderKey(name) == "Host" || len(values) == 0 {
				continue
			}
			headers[http.CanonicalHeaderKey(name)] = values[0]
		}
		parts[i] = nasUploadProbePart{URL: presigned.URL, Method: presigned.Method, Headers: headers, SizeBytes: sizes[i]}
	}
	if err := tx.Commit(ctx); err != nil {
		util.WriteError(w, http.StatusInternalServerError, "commit upload probe failed")
		return
	}
	util.WriteJSON(w, http.StatusOK, nasUploadProbeResponse{
		Enabled: true, Due: true, RetryAfterSec: int(interval.Seconds()),
		ProbeID: probeID, SizeBytes: size, Streams: streams, ExpiresAt: &expires, Parts: parts,
	})
}

// handleAccountConnectionUploadProbeResult records one probe result and then
// deletes the probe objects. A probe is reported at most once.
func (s *Server) handleAccountConnectionUploadProbeResult(w http.ResponseWriter, r *http.Request) {
	probeID, ok := parseInt64Path(w, r, "probeId")
	if !ok {
		return
	}
	var req nasUploadProbeResultRequest
	if err := util.DecodeJSON(r, &req); err != nil {
		util.WriteError(w, http.StatusBadRequest, err.Error())
		return
	}
	ctx := r.Context()
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		util.WriteError(w, http.StatusInternalServerError, "begin upload probe result failed")
		return
	}
	defer func() { _ = tx.Rollback(ctx) }()
	connectionID, ok := s.nasUploadProbeConnection(ctx, tx, w, r)
	if !ok {
		return
	}
	var sizeBytes int64
	var reportedAt *time.Time
	var now time.Time
	var prefix string
	var streams int
	err = tx.QueryRow(ctx, `SELECT size_bytes,reported_at,now(),object_prefix,streams FROM nas_upload_probes WHERE id=$1 AND connection_id=$2 FOR UPDATE`,
		probeID, connectionID).Scan(&sizeBytes, &reportedAt, &now, &prefix, &streams)
	if errors.Is(err, pgx.ErrNoRows) {
		util.WriteError(w, http.StatusNotFound, "upload probe not found")
		return
	}
	if err != nil {
		util.WriteError(w, http.StatusInternalServerError, "load upload probe failed")
		return
	}
	if reportedAt != nil {
		util.WriteError(w, http.StatusConflict, "upload probe already reported")
		return
	}
	if err := validateNASUploadProbeResult(req, sizeBytes, now); err != nil {
		util.WriteError(w, http.StatusBadRequest, err.Error())
		return
	}
	if _, err := tx.Exec(ctx, `
		UPDATE nas_upload_probes SET reported_at=now(),started_at=$2,bytes_uploaded=$3,duration_ms=$4,error=$5,
		  client_version=CASE WHEN $6<>'' THEN $6 ELSE client_version END,
		  client_phase_start=$7,client_phase_end=$8,joined_transfer_active=$9,bytes_pulled_during=$10
		WHERE id=$1`,
		probeID, req.StartedAt, req.BytesUploaded, req.DurationMS, req.Error, req.ClientVersion,
		req.ClientPhaseStart, req.ClientPhaseEnd, req.JoinedTransferActive, req.BytesPulledDuring); err != nil {
		util.WriteError(w, http.StatusInternalServerError, "record upload probe result failed")
		return
	}
	if err := tx.Commit(ctx); err != nil {
		util.WriteError(w, http.StatusInternalServerError, "commit upload probe result failed")
		return
	}
	// Delete now so a finished probe does not hold storage for the TTL, but do
	// not mark it: its presigned URLs can still write until expiry (a stream
	// cut short by the client's time cap may even land later). The sweep marks
	// it only once no URL can write any more.
	if err := s.r2.DeleteObjects(ctx, nasUploadProbeKeys(prefix, streams)); err != nil {
		log.Printf("nas upload probe %d: delete after report: %v", probeID, err)
	}
	s.sweepNASUploadProbes(ctx)
	util.WriteJSON(w, http.StatusOK, map[string]any{
		"ok": true, "mbps": nasUploadProbeMbps(req.BytesUploaded, req.DurationMS),
	})
}

// sweepNASUploadProbes deletes, and marks deleted, the objects of every probe
// whose presigned targets expired more than a grace period ago, reported or
// not. Only then can no URL write the keys again, so the mark is final. It is best effort: a failure leaves the row for
// the next sweep and never fails the caller's request.
func (s *Server) sweepNASUploadProbes(ctx context.Context) {
	if s.r2 == nil {
		return
	}
	rows, err := s.pool.Query(ctx, `
		SELECT id,object_prefix,streams FROM nas_upload_probes
		WHERE objects_deleted_at IS NULL AND expires_at < now() - $1::interval
		ORDER BY id LIMIT $2`, fmt.Sprintf("%d seconds", int(nasUploadProbeSweepGrace.Seconds())), nasUploadProbeSweepLimit)
	if err != nil {
		log.Printf("nas upload probe sweep: list: %v", err)
		return
	}
	type candidate struct {
		id      int64
		prefix  string
		streams int
	}
	var candidates []candidate
	for rows.Next() {
		var c candidate
		if err := rows.Scan(&c.id, &c.prefix, &c.streams); err != nil {
			rows.Close()
			log.Printf("nas upload probe sweep: scan: %v", err)
			return
		}
		candidates = append(candidates, c)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		log.Printf("nas upload probe sweep: rows: %v", err)
		return
	}
	for _, c := range candidates {
		if err := s.r2.DeleteObjects(ctx, nasUploadProbeKeys(c.prefix, c.streams)); err != nil {
			log.Printf("nas upload probe sweep: delete probe %d: %v", c.id, err)
			continue
		}
		if _, err := s.pool.Exec(ctx, `UPDATE nas_upload_probes SET objects_deleted_at=now() WHERE id=$1 AND objects_deleted_at IS NULL`, c.id); err != nil {
			log.Printf("nas upload probe sweep: mark probe %d: %v", c.id, err)
		}
	}
}
