BEGIN;

-- Additive: periodic NAS upload speed probes. The server issues presigned PUT
-- targets under nas-probes/, the NAS client uploads generated bytes and reports
-- wall time, and the server deletes the probe objects afterwards (or sweeps
-- them once the target expires unreported).
CREATE TABLE IF NOT EXISTS nas_upload_probes (
  id BIGSERIAL PRIMARY KEY,
  connection_id BIGINT NOT NULL REFERENCES connections(id) ON DELETE CASCADE,
  object_prefix TEXT NOT NULL UNIQUE,
  size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
  streams INTEGER NOT NULL CHECK (streams BETWEEN 1 AND 16),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  reported_at TIMESTAMPTZ,
  client_version TEXT NOT NULL DEFAULT '',
  started_at TIMESTAMPTZ,
  bytes_uploaded BIGINT CHECK (bytes_uploaded >= 0),
  duration_ms BIGINT CHECK (duration_ms >= 1),
  error TEXT NOT NULL DEFAULT '',
  client_phase_start TEXT NOT NULL DEFAULT '',
  client_phase_end TEXT NOT NULL DEFAULT '',
  joined_transfer_active BOOLEAN NOT NULL DEFAULT false,
  bytes_pulled_during BIGINT NOT NULL DEFAULT 0 CHECK (bytes_pulled_during >= 0),
  objects_deleted_at TIMESTAMPTZ,
  CHECK ((reported_at IS NULL AND bytes_uploaded IS NULL AND duration_ms IS NULL)
    OR (reported_at IS NOT NULL AND bytes_uploaded IS NOT NULL AND duration_ms IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS nas_upload_probes_connection_created_idx
  ON nas_upload_probes (connection_id, created_at DESC);
CREATE INDEX IF NOT EXISTS nas_upload_probes_undeleted_idx
  ON nas_upload_probes (expires_at) WHERE objects_deleted_at IS NULL;

COMMIT;
