package main

import (
	"strings"
	"testing"
)

// sampleJar mimics a real yt-dlp Chrome export: the Netscape header, YouTube/Google
// sign-in cookies (including an HttpOnly SID line), and a spread of unrelated sites
// (trackers, banking, gov, foreign) that must all be dropped.
const sampleJar = "# Netscape HTTP Cookie File\n" +
	"# This file is generated by yt-dlp.  Do not edit.\n" +
	"\n" +
	".youtube.com\tTRUE\t/\tTRUE\t9999999999\tLOGIN_INFO\tabc123\n" +
	"#HttpOnly_.google.com\tTRUE\t/\tTRUE\t9999999999\tSID\tsidval\n" +
	".google.com\tTRUE\t/\tTRUE\t9999999999\tSAPISID\tsapival\n" +
	"accounts.google.com\tFALSE\t/\tTRUE\t9999999999\tACCOUNT_CHOOSER\tx\n" +
	".googlevideo.com\tTRUE\t/\tTRUE\t9999999999\tGVID\ty\n" +
	"i.ytimg.com\tFALSE\t/\tFALSE\t9999999999\tPREF\tz\n" +
	".youtu.be\tTRUE\t/\tTRUE\t9999999999\tYTBE\tq\n" +
	".media.net\tTRUE\t/\tFALSE\t9999999999\tvisitor\ttrack1\n" +
	".yandex.ru\tTRUE\t/\tFALSE\t9999999999\tyandexuid\ttrack2\n" +
	"www.boston.gov\tFALSE\t/\tTRUE\t9999999999\tsession\tgov1\n" +
	".mybank.com\tTRUE\t/\tTRUE\t9999999999\tauth\tbank1\n" +
	".notgoogle.com\tTRUE\t/\tTRUE\t9999999999\tspoof\tbad1\n" +
	".google.com.evil.net\tTRUE\t/\tTRUE\t9999999999\tspoof\tbad2\n"

func TestFilterCookieLinesKeepsOnlyAllowedDomains(t *testing.T) {
	out, kept := filterCookieLines([]byte(sampleJar))
	if kept != 7 {
		t.Fatalf("kept = %d, want 7", kept)
	}
	s := string(out)

	// Header comment lines are preserved.
	if !strings.Contains(s, "# Netscape HTTP Cookie File") {
		t.Errorf("filtered jar dropped the Netscape header line")
	}

	// Every allowed domain survives; the HttpOnly SID line is kept verbatim.
	for _, want := range []string{".youtube.com", "#HttpOnly_.google.com", "accounts.google.com", ".googlevideo.com", "i.ytimg.com", ".youtu.be"} {
		if !strings.Contains(s, want) {
			t.Errorf("filtered jar dropped allowed domain line %q", want)
		}
	}

	// Every unrelated site is dropped, including suffix-spoofing lookalikes.
	for _, bad := range []string{"media.net", "yandex.ru", "boston.gov", "mybank.com", "notgoogle.com", "google.com.evil.net", "track1", "bank1", "spoof"} {
		if strings.Contains(s, bad) {
			t.Errorf("filtered jar kept disallowed content %q", bad)
		}
	}

	// The filtered jar still reads as an authenticated login.
	total, hasAuth := inspectCookieBytes(out)
	if total != 7 {
		t.Errorf("inspectCookieBytes total = %d, want 7", total)
	}
	if !hasAuth {
		t.Errorf("inspectCookieBytes hasAuth = false, want true (SID/LOGIN_INFO present)")
	}
}

func TestCookieDomainAllowed(t *testing.T) {
	cases := map[string]bool{
		"youtube.com":              true,
		".youtube.com":             true,
		"m.youtube.com":            true,
		"youtu.be":                 true,
		".google.com":              true,
		"accounts.google.com":      true,
		"rr1.sn-x.googlevideo.com": true,
		"i.ytimg.com":              true,
		"media.net":                false,
		"yandex.ru":                false,
		"boston.gov":               false,
		"notgoogle.com":            false,
		"google.com.evil.net":      false,
		"":                         false,
	}
	for domain, want := range cases {
		if got := cookieDomainAllowed(domain); got != want {
			t.Errorf("cookieDomainAllowed(%q) = %v, want %v", domain, got, want)
		}
	}
}
