(()=>{'use strict';let latest=null;const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function selected(r){return (latest?.repairs||[]).filter(x=>x.recording_id===r.id&&x.local_date>=r.start&&x.local_date<=r.end&&(!x.collections||x.collections.includes(window.coverageApp?.meta.mode||'audited')))}
function fileURL(path,download=false){const u=new URL(path,location.origin);if(/^[a-f0-9]{32}$/.test(latest?.generation||''))u.searchParams.set('generation',latest.generation);if(download)u.searchParams.set('download','1');return u.pathname+u.search}
function registered(r){const x=latest?.current_stream_counts?.[String(r.id)];return x&&(!x.period||(x.period[0]===r.start&&x.period[1]===r.end))?x:null}
const measured=x=>typeof x==='number'&&Number.isFinite(x),fmt=(x,d=1)=>measured(x)?x.toFixed(d):'Not measured';
function mediaNote(r){const x=registered(r);if(!x)return '';const amount=(v,unit)=>measured(v)?fmt(v,2)+' '+unit:'Not measured',share=v=>measured(v)?fmt(v)+'%':'Not measured';return `Registered video time is measured playback duration in the current downloadable partition; separate from source timestamp coverage and seam review. 30m+: ${x.files_at_least_30m??'Not measured'} files; ${amount(x.media_hours_at_least_30m,'h')}; share ${share(x.pct_registered_media_at_least_30m)}. 55m+: ${x.files_at_least_55m??'Not measured'} files; ${amount(x.media_hours_at_least_55m,'h')}; share ${share(x.pct_registered_media_at_least_55m)}. ${x.media_unknown_file_count??'Unknown'} files have unmeasured duration${x.media_unknown_file_count>0?'; known measured portion '+amount(measured(x.known_media_seconds)?x.known_media_seconds/3600:null,'h'):''}. Published ${latest.published_at||latest.updated_at||'unknown'}; generation ${latest.generation||'unknown'}.`}
function mediaDetail(r){const x=registered(r);if(!x)return '';return `<details class="registered-media-details"><summary>Registered video time details</summary><p>${esc(mediaNote(r))}</p></details>`}
function currentParts(r,h){return registered(r)&&window.projectCurrentDeliveryParts?window.projectCurrentDeliveryParts(h[9],selected(r)):h[9]}
function summary(r){const x=registered(r);if(x)return `${Number.isFinite(r.parts)?r.parts.toLocaleString()+' original parts → ':''}${(x.current_files??x.files).toLocaleString()} current files · ${(x.current_assemblies??x.replacements??0).toLocaleString()} assemblies · ${measured(x.registered_media_hours_measured)?fmt(x.registered_media_hours_measured,2)+' h registered video time':'Registered video time not fully measured'}${measured(x.pct_registered_media_at_least_30m)?' · '+fmt(x.pct_registered_media_at_least_30m)+'% in 30m+ pieces':''}`;const a=selected(r);return a.length?`${a.length} verified assembled outputs · ${(a.reduce((s,x)=>s+x.seconds,0)/60).toFixed(1)} min · current export ${(r.currentExportFiles??r.parts-a.reduce((s,x)=>s+x.parts_reduced,0)).toLocaleString()} files (${a.reduce((s,x)=>s+x.parts_reduced,0)} fewer)`:''}
function modelLabel(x){const v=String(x.production_version||'');if(v==='39'||v==='49')return 'V'+v;return x.kind==='reviewed'?'human-reviewed':'strict-rule'}
function detail(r){const a=selected(r),media=mediaDetail(r);return a.length?`<div class="growth-detail">${media}<details class="verified-growth"><summary>All current verified assemblies</summary><p>${esc(summary(r))}. The current export contains these replacements once. These replacements conserve encoded packets and strictly decode; perfect-stitch certification still requires review.</p>${a.map(x=>`<article><b>${esc(x.local_date)} · hour ${x.hour} · ${(x.seconds/60).toFixed(1)} minutes</b><p>${x.input_parts} original parts → one verified ${esc(modelLabel(x))} assembly</p><code class="nas-path">${esc(x.path)}</code><p><a href="${esc(fileURL(x.file_url,true))}" download>Download assembled output</a> · <button class="growth-play" data-url="${esc(fileURL(x.file_url))}">Inspect playback</button></p></article>`).join('')}</details></div>`:media?`<div class="growth-detail">${media}</div>`:''}
function refresh(){const app=window.coverageApp;if(!app)return;for(const r of app.meta.streams){r.currentExportFiles=latest?.current_stream_counts?.[String(r.id)]?.files;r.verifiedAssemblySeconds=selected(r).reduce((s,x)=>s+x.seconds,0);const row=document.querySelector('.stream-row[data-stream="'+r.id+'"]');if(row){let p=row.querySelector('.growth-summary');if(!p){p=document.createElement('p');p.className='summary growth-summary';row.querySelector('.stream-label').append(p)}p.textContent=summary(r);p.title=mediaNote(r);p.setAttribute('aria-label',summary(r)+(mediaNote(r)?'. '+mediaNote(r):''))}}const body=document.querySelector('#detail-body');if(body&& !document.querySelector('#details').hidden){const r=app.meta.streams.find(r=>r.name===document.querySelector('#detail-title').textContent);if(r){let slot=body.querySelector('.growth-detail');if(!slot){slot=document.createElement('div');slot.className='growth-detail';body.prepend(slot)}const assemblyListOpen=slot.querySelector('.verified-growth')?.open;slot.outerHTML=detail(r);if(assemblyListOpen&&body.querySelector('.verified-growth'))body.querySelector('.verified-growth').open=true}}let s=document.querySelector('#growth-status');if(!s){s=document.createElement('p');s.id='growth-status';s.className='accounting';document.querySelector('#continuity-summary').after(s)}if(latest?.current_file_count){const count=document.querySelector('#stream-count');if(count)count.textContent=`${document.querySelectorAll('.stream-row').length} of ${app.meta.streams.length} streams · ${latest.current_file_count.toLocaleString()} current files`;}const a=(latest?.repairs||[]);const v39=a.filter(x=>String(x.production_version)==='39').length,v49=a.filter(x=>String(x.production_version)==='49').length;s.textContent=`${a.length.toLocaleString()} verified assemblies · V49 rollout: ${v49.toLocaleString()} V49, ${v39.toLocaleString()} V39 published. Earlier verified assemblies remain included. Updates every 15 seconds; unfinished joins are excluded.`}
async function poll(){try{const r=await fetch('/api/coverage-growth',{cache:'no-store'});if(!r.ok)throw Error();latest=await r.json();refresh();window.dispatchEvent(new CustomEvent('coverage-growth-update',{detail:latest}))}catch(e){} }
window.coverageGrowth={summary,detail,modelLabel,fileURL,mediaNote,currentParts,replacement:(r,id)=>selected(r).find(x=>x.input_ids?.some(v=>String(v)===String(id)))};document.addEventListener('click',e=>{const b=e.target.closest('.growth-play');if(!b)return;let v=b.closest('article').querySelector('video');if(!v){v=document.createElement('video');v.controls=true;v.playsInline=true;v.preload='none';v.style.width='100%';v.src=b.dataset.url;v.defaultPlaybackRate=2;v.playbackRate=2;b.closest('article').append(v)}v.play().catch(()=>{})});new MutationObserver(refresh).observe(document.querySelector('#details'),{attributes:true,attributeFilter:['hidden']});document.addEventListener('change',e=>{if(e.target.id==='detail-day'||e.target.id==='detail-hour')setTimeout(refresh,0)});window.addEventListener('coverage-ready',refresh);setInterval(poll,15000);setTimeout(poll,500);})();
