/* Progressive delivery feedback; keep verified content visible during refresh. */
(()=>{'use strict';const $=s=>document.querySelector(s),api='/api/v1/global-street-scores-delivery/',fetchOriginal=window.fetch.bind(window);let active=0,seen=new WeakSet();
const streams=$('#streams');if(streams&&!streams.children.length)streams.innerHTML=Array.from({length:5},()=>'<div class="loading-row" aria-hidden="true"><div class="loading-thumb skeleton"></div><div class="loading-lines"><i class="skeleton"></i><i class="skeleton short"></i></div><div class="loading-days">'+Array.from({length:14},()=>'<i class="skeleton"></i>').join('')+'</div></div>').join('');
let indicator=document.createElement('span');indicator.className='refresh-indicator';indicator.setAttribute('role','status');indicator.setAttribute('aria-live','polite');$('.view-status')?.append(indicator);
function pending(delta){active=Math.max(0,active+delta);if(window.coverageApp)indicator.textContent=active?'Updating verified files…':(indicator.dataset.freshness||'');}
function rowFor(raw){try{const u=new URL(raw,location.origin),p=u.searchParams.get('path')||'',id=new URL(p,location.origin).searchParams.get('stream');return id?document.querySelector('.stream-row[data-stream="'+Number(id)+'"]'):null}catch(e){return null}}
window.fetch=async(input,init)=>{const raw=typeof input==='string'||input instanceof URL?String(input):input.url;const tracked=raw.includes(api)||raw.includes('/api/coverage-');if(!tracked)return fetchOriginal(input,init);const row=rowFor(raw);row?.classList.add('inventory-loading');pending(1);try{const result=await fetchOriginal(input,init);if(result.ok&&window.coverageApp&&raw.includes('growth'))indicator.dataset.lastUpdated=new Date().toISOString();return result}finally{row?.classList.remove('inventory-loading');pending(-1)}};
function watch(){for(const img of document.querySelectorAll('.stream-image img')){if(seen.has(img))continue;seen.add(img);const wrap=img.closest('.stream-image');wrap?.classList.add('image-loading');const done=()=>wrap?.classList.remove('image-loading');img.addEventListener('load',done,{once:true});img.addEventListener('error',()=>{done();wrap?.classList.add('image-failed');if(wrap&&!wrap.querySelector('.image-status')){const p=document.createElement('span');p.className='image-status';p.textContent='Image unavailable';wrap.append(p)}},{once:true});if(img.complete&&img.naturalWidth)done()}
const fatal=$('#fatal');if(fatal&&!fatal.hidden&&!fatal.querySelector('button')){const b=document.createElement('button');b.className='inline-retry';b.textContent='Retry';b.onclick=()=>location.reload();fatal.append(' ',b)}}
window.addEventListener('coverage-growth-update',e=>{const updated=e.detail?.published_at;if(updated){indicator.dataset.freshness='Updated '+new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'UTC'}).format(new Date(updated))+' UTC';pending(0)}});
new MutationObserver(watch).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['hidden','src']});watch();
document.addEventListener('click',e=>{const a=e.target.closest('a[download]');if(!a||a.href.includes('script')||a.href.endsWith('.py'))return;let status=a.parentElement.querySelector('.download-feedback');if(!status){status=document.createElement('span');status.className='download-feedback';status.setAttribute('role','status');a.parentElement.append(status)}status.textContent='Download requested; your browser handles the transfer.'});
})();
