'use strict';
(()=>{const qs=s=>document.querySelector(s);let stream,collection,record,reference,partToken=0,streamToken=0,current={},ranges,totalParts=0;
const scope=()=>['best','available'].includes(window.coverageApp?.meta.mode)?window.coverageApp.meta.mode:'audited';
async function request(query,body){const r=await fetch('/api/coverage-reviews'+query,{method:body?'POST':'GET',cache:'no-store',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});let d;try{d=await r.json()}catch(e){throw Error('Manual review service unavailable. Your existing reviews are preserved.')}if(!r.ok)throw Error(d.error||'Review request failed ('+r.status+').');return d;}
function reviews(d){const list=Array.isArray(d.reviews)?d.reviews:Object.values(d.reviews||{});return Object.fromEntries(list.map(r=>[String(r.output_id??r.id),r]));}
function union(xs){xs=xs.filter(x=>x[1]>x[0]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let total=0,a,b;for(const[x,y]of xs){if(a===undefined){a=x;b=y}else if(x>b){total+=b-a;a=x;b=y}else b=Math.max(b,y)}return total+(a===undefined?0:b-a);}
function progress(){const el=qs('#manual-progress');if(!el)return;const items=Object.values(current),good=items.filter(x=>x.verdict==='good'),issue=items.filter(x=>x.verdict==='issue'),uncertain=items.filter(x=>x.verdict==='uncertain');let text=`Human-reviewed parts: ${good.length} good · ${issue.length} with issues · ${uncertain.length} uncertain. ${Math.max(0,totalParts-items.length).toLocaleString()} unreviewed. Unreviewed parts have no human quality verdict.`;if(['best','available'].includes(scope())&&ranges&&record){const map=ranges.by_output_id||ranges.outputs||{},seconds=union(good.flatMap(x=>{const entry=map[String(x.output_id??x.id)];return entry?.sha256&&entry.sha256!==x.sha256?[]:entry?.ranges||entry||[]}));if(seconds<=record.captured_scheduled_seconds+.001)text+=` User-marked good parts represent ${(seconds/record.captured_scheduled_seconds*100).toFixed(2)}% of this captured timeline (${(seconds/3600).toFixed(2)} h).`;else text+=' Reviewed timeline accounting unavailable.';}el.textContent=text;qs('#detail-body').querySelectorAll('.detail-part').forEach(article=>{const id=article.id.slice(5),r=current[id];let badge=article.querySelector('.review-badge');if(!badge){badge=document.createElement('p');badge.className='review-badge';article.querySelector('.part-heading').after(badge)}badge.textContent=r?'Human review: '+({good:'reviewed good',issue:'issue found',uncertain:'uncertain'}[r.verdict]||r.verdict):'Human review: unreviewed';});}
function stop(){++partToken;reference=null;const form=qs('#manual-review-form');if(form)form.remove();}
async function show(r){const token=++streamToken;stream=r.id;collection=scope();record=r.readiness;current={};ranges=null;const el=qs('#manual-progress');if(el)el.textContent='Loading saved manual reviews…';try{const d=await request('?stream='+stream+'&scope='+collection);if(token!==streamToken)return;current=reviews(d);totalParts=d.parts;progress();if(['best','available'].includes(collection)){const filename=record?.range_data||record?.ranges_file||record?.review_ranges_file||window.coverageApp.readiness?.range_assets?.[String(stream)]?.filename;if(filename){const response=await fetch('/vid/stitching-coverage/data/'+filename,{cache:'no-store'});if(!response.ok)throw Error('Exact reviewed-timeline ranges unavailable.');const data=await response.json();if(token!==streamToken)return;ranges=data;progress();}}}catch(e){if(token===streamToken&&qs('#manual-progress'))qs('#manual-progress').textContent=e.message;}}
async function selectPart(id){stop();const token=partToken,box=qs('#review-preview');const form=document.createElement('section');form.id='manual-review-form';const title=document.createElement('h4');title.textContent='Record your part review';const help=document.createElement('p');help.textContent='After reviewing this whole part, record your judgment. Seam-only audits belong in the algorithm canary. Notes are saved with a verdict.';const note=document.createElement('textarea');note.id='manual-note';note.maxLength=1000;note.rows=3;note.setAttribute('aria-label','Optional note for this part review');note.placeholder='Optional note';const actions=document.createElement('div');actions.className='manual-review-actions';const status=document.createElement('p');status.id='manual-save-status';status.setAttribute('role','status');status.textContent='Checking immutable output identity…';for(const[verdict,label]of[['good','Reviewed good'],['issue','Issue found'],['uncertain','Unsure'],['clear','Clear review']]){const b=document.createElement('button');b.textContent=label;b.dataset.verdict=verdict;b.disabled=true;b.onclick=()=>save(verdict,note.value,token);actions.append(b)}form.append(title,help,note,actions,status);box.append(form);try{const d=await request('?output='+id+'&scope='+collection);if(token!==partToken)return;reference={output_id:d.output_id??d.id,sha256:d.sha256,stream_id:d.recording_id??stream,scope:collection};if(!reference.output_id||!/^[a-f0-9]{64}$/.test(reference.sha256))throw Error('Verified output identity unavailable.');const review=d.review||d.current_review;if(review)note.value=review.note||'';status.textContent=review?'Saved verdict: '+review.verdict:'No human review yet.';actions.querySelectorAll('button').forEach(b=>b.disabled=false);}catch(e){if(token===partToken)status.textContent=e.message;}}
async function save(verdict,note,token){if(token!==partToken||!reference)return;const identity={...reference},form=qs('#manual-review-form'),status=qs('#manual-save-status');form.querySelectorAll('button').forEach(b=>b.disabled=true);status.textContent='Saving your review…';try{await request('',{...identity,verdict,note});if(token!==partToken)return;status.textContent='Review saved.';const d=await request('?stream='+stream+'&scope='+collection);if(token!==partToken)return;current=reviews(d);totalParts=d.parts;progress();}catch(e){if(token===partToken)status.textContent=e.message;}finally{if(token===partToken)form.querySelectorAll('button').forEach(b=>b.disabled=false);}}
window.manualReviews={show,selectPart,stop,union};})();
