package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/daydemir/stoarama/backend/internal/config"
	"github.com/daydemir/stoarama/backend/internal/db"
	"github.com/daydemir/stoarama/backend/internal/email"
)

func runAlerts(ctx context.Context, cfg config.Config, args []string) {
	if len(args) < 1 {
		log.Fatalf("usage: stoaramactl alerts <send-test-email|history> ...")
	}
	switch args[0] {
	case "send-test-email":
		runAlertsSendTestEmail(ctx, cfg, args[1:])
	case "history":
		runAlertsHistory(ctx, cfg, args[1:])
	default:
		log.Fatalf("unknown alerts subcommand %q", args[0])
	}
}

func runAlertsSendTestEmail(ctx context.Context, cfg config.Config, args []string) {
	fs := flag.NewFlagSet("alerts send-test-email", flag.ExitOnError)
	to := fs.String("to", "", "optional recipient email; defaults to all active verified admins")
	streamID := fs.Int64("stream-id", 434, "stream id to reference in the test alert")
	streamName := fs.String("stream-name", "Test stream", "stream name to reference in the test alert")
	reason := fs.String("reason", "capture_runtime_stopped", "test incident reason")
	_ = fs.Parse(args)

	mailer, err := email.NewSender(email.Config{
		Provider:  cfg.EmailProvider,
		From:      cfg.EmailFrom,
		ReplyTo:   cfg.EmailReplyTo,
		ResendKey: cfg.EmailResendAPIKey,
	})
	if err != nil {
		log.Fatalf("init email sender: %v", err)
	}

	recipients := []string{}
	if strings.TrimSpace(*to) != "" {
		recipients = append(recipients, strings.TrimSpace(*to))
	} else {
		pool, err := db.Open(ctx, cfg.DatabaseURL)
		if err != nil {
			log.Fatalf("open db: %v", err)
		}
		defer pool.Close()
		rows, err := pool.Query(ctx, `
			SELECT email
			FROM accounts
			WHERE role='admin'
			  AND status='active'
			  AND email_verified_at IS NOT NULL
			ORDER BY id ASC
		`)
		if err != nil {
			log.Fatalf("query admin recipients: %v", err)
		}
		defer rows.Close()
		for rows.Next() {
			var addr string
			if err := rows.Scan(&addr); err != nil {
				log.Fatalf("scan admin recipient: %v", err)
			}
			addr = strings.TrimSpace(addr)
			if addr != "" {
				recipients = append(recipients, addr)
			}
		}
		if err := rows.Err(); err != nil {
			log.Fatalf("iterate admin recipients: %v", err)
		}
	}
	if len(recipients) == 0 {
		log.Fatalf("no recipients found")
	}

	baseURL := strings.TrimRight(cfg.AppBaseURL, "/")
	if baseURL == "" {
		baseURL = "https://stoarama.com"
	}
	subject := fmt.Sprintf("[Stoarama] Recording problem: %s (#%d)", strings.TrimSpace(*streamName), *streamID)
	body := fmt.Sprintf(
		"Stoarama detected a recording problem that persisted past the alert threshold.\n\nStream: %s (#%d)\nReason: %s\nServer: test-server\nRuntime status: stopped\nLast frame: %s\nRuntime error: synthetic test alert generated by stoaramactl\n\nView: %s/dashboard/stream/%d\n",
		strings.TrimSpace(*streamName),
		*streamID,
		strings.TrimSpace(*reason),
		time.Now().UTC().Add(-10*time.Minute).Format(time.RFC3339),
		baseURL,
		*streamID,
	)

	for _, addr := range recipients {
		if _, err := mailer.Send(ctx, email.Message{
			To:          addr,
			Subject:     subject,
			PlainText:   body,
			MessageType: "recording_problem_test",
		}); err != nil {
			log.Fatalf("send test email to %s: %v", addr, err)
		}
		fmt.Printf("sent test alert email to %s\n", addr)
	}
}

func runAlertsHistory(ctx context.Context, cfg config.Config, args []string) {
	fs := flag.NewFlagSet("alerts history", flag.ExitOnError)
	limit := fs.Int("limit", 50, "row limit")
	status := fs.String("status", "", "optional provider status filter")
	streamID := fs.Int64("stream-id", 0, "optional stream id filter")
	_ = fs.Parse(args)

	pool, err := db.Open(ctx, cfg.DatabaseURL)
	if err != nil {
		log.Fatalf("open db: %v", err)
	}
	defer pool.Close()

	where := []string{"1=1"}
	sqlArgs := make([]any, 0, 4)
	if strings.TrimSpace(*status) != "" {
		sqlArgs = append(sqlArgs, strings.TrimSpace(*status))
		where = append(where, fmt.Sprintf("e.provider_status=$%d", len(sqlArgs)))
	}
	if *streamID > 0 {
		sqlArgs = append(sqlArgs, *streamID)
		where = append(where, fmt.Sprintf("e.stream_id=$%d", len(sqlArgs)))
	}
	sqlArgs = append(sqlArgs, *limit)
	rows, err := pool.Query(ctx, fmt.Sprintf(`
		SELECT e.id, e.stream_id, s.name, e.recipient, e.provider, e.provider_message_id, e.provider_status, e.subject, e.sent_at, e.delivered_at, e.opened_at, e.bounced_at, e.error_text, e.created_at
		FROM alert_delivery_events e
		JOIN streams s ON s.id=e.stream_id
		WHERE %s
		ORDER BY e.created_at DESC, e.id DESC
		LIMIT $%d
	`, strings.Join(where, " AND "), len(sqlArgs)), sqlArgs...)
	if err != nil {
		log.Fatalf("query alert history: %v", err)
	}
	defer rows.Close()
	count := 0
	for rows.Next() {
		var (
			id, rowStreamID                                                          int64
			name, recipient, provider, messageID, providerStatus, subject, errorText string
			sentAt, deliveredAt, openedAt, bouncedAt                                 *time.Time
			createdAt                                                                time.Time
		)
		if err := rows.Scan(&id, &rowStreamID, &name, &recipient, &provider, &messageID, &providerStatus, &subject, &sentAt, &deliveredAt, &openedAt, &bouncedAt, &errorText, &createdAt); err != nil {
			log.Fatalf("scan alert history: %v", err)
		}
		count++
		fmt.Printf("id=%d stream_id=%d status=%s provider=%s message_id=%q recipient=%s sent_at=%v delivered_at=%v opened_at=%v bounced_at=%v created_at=%s subject=%q error=%q\n",
			id, rowStreamID, providerStatus, provider, messageID, recipient, sentAt, deliveredAt, openedAt, bouncedAt, createdAt.UTC().Format(time.RFC3339), subject, errorText)
	}
	if err := rows.Err(); err != nil {
		log.Fatalf("iterate alert history: %v", err)
	}
	fmt.Printf("rows=%d\n", count)
}
