package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/daydemir/stoarama/backend/internal/config"
	"github.com/daydemir/stoarama/backend/internal/db"
	"github.com/daydemir/stoarama/backend/internal/email"
)

func runAlerts(ctx context.Context, cfg config.Config, args []string) {
	if len(args) < 1 {
		log.Fatalf("usage: stoaramactl alerts send-test-email [--to email@example.com] [--stream-id N --stream-name NAME --reason capture_runtime_stopped]")
	}
	switch args[0] {
	case "send-test-email":
		runAlertsSendTestEmail(ctx, cfg, args[1:])
	default:
		log.Fatalf("unknown alerts subcommand %q", args[0])
	}
}

func runAlertsSendTestEmail(ctx context.Context, cfg config.Config, args []string) {
	fs := flag.NewFlagSet("alerts send-test-email", flag.ExitOnError)
	to := fs.String("to", "", "optional recipient email; defaults to all active verified admins")
	streamID := fs.Int64("stream-id", 434, "stream id to reference in the test alert")
	streamName := fs.String("stream-name", "Test stream", "stream name to reference in the test alert")
	reason := fs.String("reason", "capture_runtime_stopped", "test incident reason")
	_ = fs.Parse(args)

	mailer, err := email.NewSender(email.Config{
		Provider:  cfg.EmailProvider,
		From:      cfg.EmailFrom,
		ReplyTo:   cfg.EmailReplyTo,
		ResendKey: cfg.EmailResendAPIKey,
	})
	if err != nil {
		log.Fatalf("init email sender: %v", err)
	}

	recipients := []string{}
	if strings.TrimSpace(*to) != "" {
		recipients = append(recipients, strings.TrimSpace(*to))
	} else {
		pool, err := db.Open(ctx, cfg.DatabaseURL)
		if err != nil {
			log.Fatalf("open db: %v", err)
		}
		defer pool.Close()
		rows, err := pool.Query(ctx, `
			SELECT email
			FROM accounts
			WHERE role='admin'
			  AND status='active'
			  AND email_verified_at IS NOT NULL
			ORDER BY id ASC
		`)
		if err != nil {
			log.Fatalf("query admin recipients: %v", err)
		}
		defer rows.Close()
		for rows.Next() {
			var addr string
			if err := rows.Scan(&addr); err != nil {
				log.Fatalf("scan admin recipient: %v", err)
			}
			addr = strings.TrimSpace(addr)
			if addr != "" {
				recipients = append(recipients, addr)
			}
		}
		if err := rows.Err(); err != nil {
			log.Fatalf("iterate admin recipients: %v", err)
		}
	}
	if len(recipients) == 0 {
		log.Fatalf("no recipients found")
	}

	baseURL := strings.TrimRight(cfg.AppBaseURL, "/")
	if baseURL == "" {
		baseURL = "https://stoarama.com"
	}
	subject := fmt.Sprintf("[Stoarama] Recording problem: %s (#%d)", strings.TrimSpace(*streamName), *streamID)
	body := fmt.Sprintf(
		"Stoarama detected a recording problem that persisted past the alert threshold.\n\nStream: %s (#%d)\nReason: %s\nServer: test-server\nRuntime status: stopped\nLast frame: %s\nRuntime error: synthetic test alert generated by stoaramactl\n\nView: %s/dashboard/stream/%d\n",
		strings.TrimSpace(*streamName),
		*streamID,
		strings.TrimSpace(*reason),
		time.Now().UTC().Add(-10*time.Minute).Format(time.RFC3339),
		baseURL,
		*streamID,
	)

	for _, addr := range recipients {
		if err := mailer.Send(ctx, email.Message{
			To:          addr,
			Subject:     subject,
			PlainText:   body,
			MessageType: "recording_problem_test",
		}); err != nil {
			log.Fatalf("send test email to %s: %v", addr, err)
		}
		fmt.Printf("sent test alert email to %s\n", addr)
	}
}
